route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        username: 'Monitoring'
        channel: ''
        api_url: ''
        text: '{{ .CommonAnnotations.summary }}'
