route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        username: 'Monitoring'
        channel: ''
        api_url: ''
        title: '{{ template "custom_title" . }}'
        text: '{{ template "custom_slack_message" . }}'

templates:
  - /alertmanager/notifications.tmpl
